"""empty message

Revision ID: 4010e6254a42
Revises: 
Create Date: 2024-06-17 20:50:37.264660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4010e6254a42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meme',
    sa.Column('id', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('text', sa.String(), nullable=False, comment='Текст мема'),
    sa.Column('image', sa.String(), nullable=False, comment='Название файла с изображением'),
    sa.Column('url_image', sa.String(), nullable=False, comment='Ссылка на изображение'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meme')
    # ### end Alembic commands ###
