from .create_meme import EXAMPLE_CREATE_MEME_RESPONSE
from .delete_meme import EXAMPLE_DELETE_MEME_RESPONSE
from .get_meme import EXAMPLE_GET_MEME_RESPONSE
from .get_memes import EXAMPLE_GET_MEMES_RESPONSE
from .update_meme import EXAMPLE_UPDATE_MEME_RESPONSE

__all__ = (
    'EXAMPLE_CREATE_MEME_RESPONSE',
    'EXAMPLE_GET_MEMES_RESPONSE',
    'EXAMPLE_UPDATE_MEME_RESPONSE',
    'EXAMPLE_DELETE_MEME_RESPONSE',
    'EXAMPLE_GET_MEME_RESPONSE'
)
